baseURL = "https://www.x2q.net"
languageCode = "en"
title = "x2q"
copyright = "x2q"

[params]
subtitle = "a blog on tech, food, and everything in between"

[params.author]
name = "X2Q"
email = "x2q@x2q.net"

[params.header]
logo = "favicon.svg"
favicon = "favicon.svg"

[params.footer]
since = 2010
